version: '3.8'

services:
  backend:
    build: ./CareerBackend
    command: gunicorn main:app -b 0.0.0.0:1034
    volumes:
      - ./CareerBackend:/CareerFinder/backend
    ports:
      - 1034:1034
    container_name: backend_service
    depends_on:
      - mysql

  frontend:  
    build: ./CareerFrontend
    command: gunicorn main:app -b 0.0.0.0:1020
    volumes:
      - ./CareerFrontend:/CareerFinder/frontend
    ports:
      - 80:1020
    depends_on:
      - backend
    container_name: frontend_service

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CareerFinder
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    container_name: mysql_database

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234     
    container_name: phpmyadmin 

    

    